import Form from "@/components/Form";
import Table from "@/components/Table";
import Head from "next/head";
import { AiOutlineUserAdd } from "react-icons/ai";

export default function Home() {
  return (
    <>
      <Head>
        <title>Employee management system</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="py-5">
        <h1 className="text-xl md:text-5xl text-center font-bold py-10">
          Employee Management System
        </h1>
        <div className="container mx-auto flex  justify-space-between align-center py-5 border-b">
          <button className="flex bg-indigo-500 items-center text-white p-2 border rounded-md hover:bg-gray-500">
            Add Employee <AiOutlineUserAdd size={20} />
          </button>
        </div>
        <div className="container mx-auto">
          <Table />
          <Form />
        </div>
      </main>
    </>
  );
}
